server:
  port: 8081



##logging
logging:
  config: classpath:logback-spring.xml
  file: saas-web
  path: /

##mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-prefix: dao.

pagehelper:
  autoDialect: true
  closeConn: true
  reasonable: true


##datasource
spring:
  datasource:
    url: jdbc:mysql://172.16.101.250:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: xyy_erp
    password: 1qaz123
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 300
    initialSize: 20
    maxWait: 6000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

  ##自定义配置文件
  profiles:
      active: config